### ISSUE TITLE
Tflite IndexError: list index out of range

### ISSUE THREAD

**Issue by erkin98** [TannerGilbert/Tensorflow-2-Object-Counting#3]
When i use tflite model which is converted from darknet yolov4 weights i get this error,its quantized float16 tflite model,and i use only one class for my model 
How can i fix this?
thanks in advance

```
C:\Users\Erkin\Desktop\tf yolov4\Tensorflow-2-Object-Counting>python tflite_cumulative_object_counting.py -m model.tflite -l labelmap.txt -v video.mp4 -a
Traceback (most recent call last):
  File "tflite_cumulative_object_counting.py", line 228, in <module>
    main()
  File "tflite_cumulative_object_counting.py", line 137, in main
    results = detect_objects(interpreter, image_pred, args.threshold)
  File "tflite_cumulative_object_counting.py", line 49, in detect_objects
    scores = get_output_tensor(interpreter, 2)
  File "tflite_cumulative_object_counting.py", line 36, in get_output_tensor
    output_details = interpreter.get_output_details()[index]
IndexError: list index out of range
```

**Comment by TannerGilbert** [comment]
This error occurs because the exported Tensorflow OD model has a different output structure than the YOLO model.

For the Tensorflow model the following code is used:
```python
boxes = get_output_tensor(interpreter, 0)
classes = get_output_tensor(interpreter, 1)
scores = get_output_tensor(interpreter, 2)
count = int(get_output_tensor(interpreter, 3))
```

If you want to use the code with a YOLO model, you'll have to rewrite this to fit the YOLO structure. For reference, take a look at [this](https://github.com/hunglc007/tensorflow-yolov4-tflite/blob/master/detect.py#L48).

If I find the time, I'll also try to create a YOLO compatible file.

**Comment by TannerGilbert** [comment]
I just added YOLO support to the script. You just need to say `--type yolo` if you're using a yolov4 or yolov3 model or `--type yolov3-tiny` if you're using a yolov3 tiny model.
